from __future__ import annotations

import re

_GREEK_NAMES = {
    "α": "alpha",
    "β": "beta",
    "γ": "gamma",
    "δ": "delta",
    "ε": "epsilon",
    "ζ": "zeta",
    "η": "eta",
    "θ": "theta",
    "ι": "iota",
    "κ": "kappa",
    "λ": "lambda",
    "μ": "mu",
    "ν": "nu",
    "ξ": "xi",
    "ο": "omicron",
    "π": "pi",
    "ρ": "rho",
    "σ": "sigma",
    "τ": "tau",
    "υ": "upsilon",
    "φ": "phi",
    "χ": "chi",
    "ψ": "psi",
    "ω": "omega",
    "Γ": "gamma",
    "Δ": "delta",
    "Θ": "theta",
    "Λ": "lambda",
    "Ξ": "xi",
    "Π": "pi",
    "Σ": "sigma",
    "Φ": "phi",
    "Ψ": "psi",
    "Ω": "omega",
}

_LATEX_GREEK = {
    "alpha": "alpha",
    "beta": "beta",
    "gamma": "gamma",
    "delta": "delta",
    "epsilon": "epsilon",
    "varepsilon": "epsilon",
    "zeta": "zeta",
    "eta": "eta",
    "theta": "theta",
    "vartheta": "theta",
    "iota": "iota",
    "kappa": "kappa",
    "lambda": "lambda",
    "mu": "mu",
    "nu": "nu",
    "xi": "xi",
    "omicron": "omicron",
    "pi": "pi",
    "varpi": "pi",
    "rho": "rho",
    "varrho": "rho",
    "sigma": "sigma",
    "varsigma": "sigma",
    "tau": "tau",
    "upsilon": "upsilon",
    "phi": "phi",
    "varphi": "phi",
    "chi": "chi",
    "psi": "psi",
    "omega": "omega",
}

_LATEX_MATH = {
    **_LATEX_GREEK,
    "int": "integral",
    "iint": "integral",
    "oint": "integral",
    "sum": "sum",
    "prod": "prod",
    "frac": "frac",
    "dfrac": "frac",
    "tfrac": "frac",
    "sqrt": "sqrt",
    "partial": "partial",
    "le": "le",
    "leq": "le",
    "leqslant": "le",
    "ge": "ge",
    "geq": "ge",
    "geqslant": "ge",
    "ne": "ne",
    "neq": "ne",
    "to": "maps_to",
    "rightarrow": "maps_to",
    "longrightarrow": "maps_to",
    "mapsto": "maps_to",
    "in": "member_of",
    "notin": "not_member_of",
    "subset": "subset_of",
    "subseteq": "subset_of",
    "supset": "superset_of",
    "supseteq": "superset_of",
    "infty": "infinity",
    "nabla": "nabla",
    "forall": "for_all",
    "exists": "exists",
    "approx": "approx",
    "equiv": "equiv",
    "oplus": "oplus",
    "otimes": "otimes",
    "cup": "union",
    "cap": "intersection",
    "wedge": "and_op",
    "vee": "or_op",
    "implies": "implies",
    "Rightarrow": "implies",
    "iff": "iff",
    "Leftrightarrow": "iff",
    "cdot": "cdot",
    "times": "times",
    "pm": "pm",
    "mp": "pm",
}

_UNICODE_MATH = {
    "∫": "integral",
    "∬": "integral",
    "∮": "integral",
    "∑": "sum",
    "∏": "prod",
    "√": "sqrt",
    "∂": "partial",
    "∈": "member_of",
    "∉": "not_member_of",
    "⊂": "subset_of",
    "⊆": "subset_of",
    "⊃": "superset_of",
    "⊇": "superset_of",
    "≤": "le",
    "⩽": "le",
    "≥": "ge",
    "⩾": "ge",
    "≠": "ne",
    "∞": "infinity",
    "→": "maps_to",
    "↦": "maps_to",
    "⟶": "maps_to",
    "∇": "nabla",
    "∀": "for_all",
    "∃": "exists",
    "≈": "approx",
    "≡": "equiv",
    "⊕": "oplus",
    "⊗": "otimes",
    "∪": "union",
    "∩": "intersection",
    "∧": "and_op",
    "∨": "or_op",
    "⟹": "implies",
    "⇒": "implies",
    "⟺": "iff",
    "⇔": "iff",
    "⋅": "cdot",
    "×": "times",
    "±": "pm",
}

_COMMAND_RE = re.compile(r"\\[a-zA-Z]+")


def tokenize_math(text: str) -> list[str]:
    if not text:
        return []
    tokens: list[str] = []
    for ch in text:
        if ch in _GREEK_NAMES:
            tokens.append(_GREEK_NAMES[ch])
        elif ch in _UNICODE_MATH:
            tokens.append(_UNICODE_MATH[ch])
    for match in _COMMAND_RE.findall(text):
        name = match[1:].lower()
        canonical = _LATEX_MATH.get(name)
        tokens.append(canonical if canonical is not None else name)
    return tokens
