"""Pydantic request/response schemas and structured model-output shapes.

Model-generated plan/quiz content is validated here before being persisted.
``QuizQuestionInput`` is the raw model output shape; the server appends the
"I don't know" option and the full ``QuizQuestion`` record is what the API
exposes and the database stores.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

GroundingMode = Literal["strict", "grounded"]


class FileRecord(BaseModel):
    """A file in the library and its ingestion state."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    display_name: str
    mime_type: str | None = None
    size_bytes: int
    sha256: str
    status: str = "pending"
    warnings: list[str] = Field(default_factory=list)
    error: str | None = None
    num_chunks: int = 0
    created_at: str
    updated_at: str


class SessionCreate(BaseModel):
    """Body for POST /api/sessions."""

    goal: str = Field(min_length=1, max_length=2000)
    file_ids: list[str] = Field(default_factory=list)
    grounding_mode: GroundingMode = "grounded"


class Session(BaseModel):
    """A learning session summary."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    title: str | None = None
    goal: str
    phase: str = "setup"
    grounding_mode: GroundingMode = "grounded"
    current_node_id: str | None = None
    nodes_since_check: int = 0
    file_ids: list[str] = Field(default_factory=list)
    created_at: str
    updated_at: str


class Message(BaseModel):
    """A persisted chat message (user or assistant)."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    session_id: str
    client_msg_id: str | None = None
    role: str
    kind: str = "text"
    content: str
    citations: list[str] = Field(default_factory=list)
    partial: int = 0
    created_at: str


class HealthReport(BaseModel):
    """GET /api/health payload."""

    status: Literal["ok", "degraded", "error"]
    model_configured: bool
    endpoint_reachable: bool | None = None
    dependency_errors: list[str] = Field(default_factory=list)
    checked_at: str


class QuizQuestionInput(BaseModel):
    """A multiple-choice question exactly as generated by the model."""

    topic: str | None = None
    difficulty: int = 3
    question: str = Field(min_length=1)
    options: list[str] = Field(min_length=2, max_length=6)
    correct_index: int = Field(ge=0)
    explanation: str | None = None

    def validate_index(self) -> bool:
        """True when ``correct_index`` points inside ``options``."""
        return 0 <= self.correct_index < len(self.options)


class QuizQuestion(BaseModel):
    """A stored quiz question including the server-appended "I don't know" option."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    session_id: str
    kind: str = "probe"
    topic: str | None = None
    difficulty: int = 3
    question: str
    options: list[str]
    correct_index: int
    explanation: str | None = None
    status: str = "pending"
    user_choice: int | None = None
    outcome: str | None = None
    created_at: str
    answered_at: str | None = None


class PlanNode(BaseModel):
    """One node in a dependency-aware learning plan."""

    node_key: str = Field(min_length=1)
    title: str = Field(min_length=1)
    description: str | None = None
    depends_on: list[str] = Field(default_factory=list)
    status: str = "pending"
    position: int = 0
    children: list[str] = Field(default_factory=list)


class Plan(BaseModel):
    """A full learning plan (model-generated, server-validated)."""

    nodes: list[PlanNode]

    def validate_dependencies(self) -> bool:
        """True when every ``depends_on`` reference names a real node."""
        keys = {n.node_key for n in self.nodes}
        return all(dep in keys for n in self.nodes for dep in n.depends_on)


class MasteryTopic(BaseModel):
    """Topic-level mastery estimate."""

    model_config = ConfigDict(from_attributes=True)

    topic: str
    label: str
    confidence: float = 0.0
    observed_count: int = 0
    correct_count: int = 0
    idk_count: int = 0
    last_assessed_at: str | None = None
    evidence: list[dict[str, Any]] = Field(default_factory=list)
    notes: str | None = None


class TurnBody(BaseModel):
    """Body for POST /api/sessions/{id}/turns."""

    message: str = Field(min_length=1, max_length=8000)
    client_msg_id: str = Field(min_length=1, max_length=200)


class RetryBody(BaseModel):
    """Body for POST /api/sessions/{id}/retry."""

    client_msg_id: str = Field(min_length=1, max_length=200)


class ProbeBody(BaseModel):
    pass


class CheckBody(BaseModel):
    pass


class QuizAnswerBody(BaseModel):
    choice_index: int | None = None
    idk: bool = False


class ReorderPlanBody(BaseModel):
    """Body for POST /api/sessions/{id}/plan/reorder."""

    node_keys: list[str] = Field(min_length=1)


class PlanNodeActionBody(BaseModel):
    """Body for plan skip/select by node_key."""

    node_key: str = Field(min_length=1)


class ExpandPlanBody(BaseModel):
    """Body for POST /api/sessions/{id}/plan/expand."""

    node_key: str = Field(min_length=1)
    detail: str | None = None


class PreferencesBody(BaseModel):
    """Partial update for learner teaching preferences."""

    depth: Literal["brief", "standard", "deep"] | None = None
    pacing: Literal["slow", "normal", "fast"] | None = None
    style: Literal["analogy-first", "examples-first", "formal-first"] | None = None
    notes: str | None = None


class Preferences(BaseModel):
    """Stored learner teaching preferences (single row, id=1)."""

    depth: Literal["brief", "standard", "deep"]
    pacing: Literal["slow", "normal", "fast"]
    style: Literal["analogy-first", "examples-first", "formal-first"]
    notes: str | None = None
    updated_at: str
